### ISSUE TITLE
More extensive documentation

### ISSUE THREAD

**Issue by Pictor13** [Jubobs/gitdags#3]
I like this extension and it is really useful for creating simple DAGs!

Would be really nice if there could be more examples to show what can be achieved with this syntax.
I imagine that could be done more than showed in the _Wiki_ example, but I cannot guess how.

Specifically I couldn't manage to:

* have **pointing arrows longer than default** (I want to represent a `git merge` but cannot get the merge-commit to point to the _master_ previous commit

<pre>
    A -- B -- -- -- E
           \       /
            C -- D
</pre>
in this case I cannot make E point to B.
I can just manage to add a middle commit; let's say B2

<pre>
    A -- B -- B2 -- E
           \       /
            C -- D
</pre>

* **draw more than two branches** (if I try to add a third line I get a compile error)

<pre>    
    A -- B -- -- -- E
     \     \       /
      \     C -- D
       \ 
        F
</pre>

**Comment by Pictor13** [comment]
Hey thanks for your update!
Yeah, your additions are enough for doing what I needed!
`xshift` was exactly what I was missing! I'll check that _TikZ/PGF_ documentation as well, even if I guess the addition in the Wiki of the examples for the most common cases/combinations would be useful for everyone :)
Good job!

**Comment by Jubobs** [comment]
Cool. I still have to write the documentation for `gitdags`, but, for now, I'll close this issue.
