### ISSUE TITLE
Adjust Distance between nodes 

### ISSUE THREAD

**Issue by amacgregor** [Jubobs/gitdags#5]
Is there a way to set a custom distance between nodes? I'm using the following code:

```
  \begin{subfigure}[c]{\textwidth}
    \centering
    \begin{tikzpicture}
      % Commit DAG
      \gitDAG[grow right sep = 2em]{
        M5[DAGedge] -- M6 -- M7 -- {
        M7 -- M8,
        M7 -- F1 -- F2 -- F3 -- F4 -- M8,
        }
      };
      \gitbranch
        {master}      % node name and text
        {above=of M7} % node placement
        {M7}
      \gitHEAD
        {above=of master} % node placement
        {master}          % target
      \gitbranch
        {feature}      % node name and text
        {below=of F4} % node placement
        {F4}
    \end{tikzpicture}
    \subcaption{\ldots{} we sync our local feature branch \texttt{git rebase master}}
  \end{subfigure}
```

Which generates the attached graph:

<img width="626" alt="screenshot 2015-07-10 09 09 31" src="https://cloud.githubusercontent.com/assets/212169/8619255/6c2e6bae-26e3-11e5-868f-88be3ec681ae.png">

However the alignment is not correct is there any way to move M8 to the right so it aligns with F4?

**Comment by calvinatintel** [comment]
Judging by the second to the last image on [SO](https://stackoverflow.com/questions/25933056/how-can-i-do-a-bugfix-on-master-and-integrate-it-into-my-less-stable-branches/25934341#25934341), it certainly seems possible. I wish the author would tell us how.

**Comment by Jubobs** [comment]
Some manual tweaking is required; same technique as in issue #3. Note that you shouldn't use `DAGedge` as you do, though.

```latex
\documentclass{article}

\usepackage{gitdags}

\begin{document}
  \begin{tikzpicture}
    % Commit DAG
    \gitDAG[grow right sep = 2em]{
      M5 -- M6 -- M7 -- {
        M7 -- M8[xshift=13.2em],      % <-----------
        M7 -- F1 -- F2 -- F3 -- F4 -- M8,
      }
    };
    \gitbranch
      {master}      % node name and text
      {above=of M7} % node placement
      {M7}
    \gitHEAD
      {above=of master} % node placement
      {master}          % target
    \gitbranch
      {feature}     % node name and text
      {below=of F4} % node placement
      {F4}
  \end{tikzpicture}
\end{document}
```

![screen shot 2015-09-30 at 20 27 13](https://cloud.githubusercontent.com/assets/7138892/10204079/aba1b5ca-67b1-11e5-9ec5-692a863ee959.png)

**Comment by calvinatintel** [comment]
Thank you @Jubobs for the response!
Is there a way to set the shift property to a group? For `yshift`, I'm finding that I need to apply it to pretty much all nodes in a branch.

**Comment by Jubobs** [comment]
@calvinatintel The method for shifting an entire part of the graph vertically is to use `branch down` option at the right place. Could you open a new issue with a minimal working example and a description of the desired output?

**Comment by Jubobs** [comment]
I can't think of a very convenient way of reducing code duplication (`yshift=-2em`), in this case. The closest thing is to use `branch down`, as shown below:

![screen shot 2015-10-04 at 11 53 51](https://cloud.githubusercontent.com/assets/7138892/10267500/b18e8a46-6a8e-11e5-9d83-a728aef036c3.png)


```latex
\gitDAG[grow right sep = 1em, branch down = 5em]{
    m1 -- {m2 ,
            u1 -- u2,
            t1 -- t2
          }
   };
  \gittag
    {mytag}       % node name and text 
    {above=of u1} % node placement
    {u1}          % target
```
