### ISSUE TITLE
Source for your diagrams in SO posts? (Question)

### ISSUE THREAD

**Issue by mindthump** [jubobs/gitdags#8]
In lieu of documentation, could you post the 'source' for the diagrams in the other SourceOverflow posts you refer to in this post?

http://stackoverflow.com/questions/1057564/pretty-git-branch-graphs

Maybe a simple example of using the Staging Area and Work Tree as well. I'm trying to figure out how to show interaction with the "remote repo" itself, as different users do pushes and pulls. (In particular how does a "rebase after a push" mess up other users.)

Thanks so much, this tool is brilliant and just what I need!

**Comment by Jubobs** [comment]
Thanks for your feedback. Believe it or not, I'm working on the documentation and it consists in a series of examples. I'm hoping to (finally!) finish it some time next week; however, I'll post an example of what you're asking for below over the weekend.

**Comment by szelpe** [comment]
Hi @Jubobs, I really enjoy using ditdags, thank you for creating it. I'm looking forward to the documentation you mentioned.
